baseurl = "https://www.plaiground.com/"
title = "Plaiground"
author = "Anush Ravi & Nikhila Ravi"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Plaiground"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
[[menu.main]]
    name = "Posts"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
[[menu.main]]
    name = "Contact"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
